[general]
	#
	# If the TFC world preset 'tfc:overworld' should be set as the default world generation when creating a new world.
	defaultWorldPreset = "tfc:overworld"

[calendar]
	#
	# The number of days in a month, for newly created worlds.
	# 
	# This can be modified in existing worlds using the /time command
	# Default: 8
	# Range: > 1
	defaultMonthLength = 8
	#
	# The start date for newly created worlds, in a number of ticks, for newly created worlds
	# This represents a number of days offset from January 1, 1000
	# The default is (5 * daysInMonth) = 40, which starts at June 1, 1000 (with the default daysInMonth = 8)
	# Default: 40
	# Range: > -1
	defaultCalendarStartDay = 40
	#
	# The month length (in minutes) for newly created worlds
	# The default (in TFC) is 24, which at 20 TPS makes one in-game hour equal to exactly one minute of real time.
	# 
	# This can be modified in existing worlds using the /time command
	defaultCalendarDayLength = 24

[debug]
	#
	# If enabled, TFC will validate that certain pieces of reloadable data fit the conditions we expect, for example heating recipes having heatable items. It will error or warn in the log if these conditions are not met.
	enableDatapackTests = false
